apiVersion: v1
kind: Service
metadata:
  name: sample-workload
spec:
  type: LoadBalancer
  selector:
    app: sample-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-workload
  labels:
    app: sample-workload
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sample-workload
  template:
    metadata:
      labels:
        app: sample-workload
    spec:
      containers:
        - name: sample-workload
          image: IMAGE
          ports:
            - containerPort: 80