AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
  JenkinsAllowedCIDR:
    Type: String
  JenkinsSSHKeyName:
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  # AMI NAME: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  AMIRegionMap:
    ap-northeast-1:
      AMI: ami-067373c206eab18c5
    ap-northeast-2:
      AMI: ami-09ca223c409420549
    ap-south-1:
      AMI: ami-0835240c6a4146612
    ap-southeast-1:
      AMI: ami-06fb4227dd8528486
    ap-southeast-2:
      AMI: ami-0e6449745600ac1da
    ca-central-1:
      AMI: ami-0419d42438dfe5215
    eu-central-1:
      AMI: ami-079024c517d22af5b
    eu-north-1:
      AMI: ami-0b4a48196ce7bed7b
    eu-west-1:
      AMI: ami-0127d62154efde733
    eu-west-2:
      AMI: ami-0fb673bc6ff8fc282
    eu-west-3:
      AMI: ami-03ceeb0f46ee38ce7
    sa-east-1:
      AMI: ami-0ccc65ecf88e9fe1a
    us-east-1:
      AMI: ami-0d57c0143330e1fa7
    us-east-2:
      AMI: ami-01237fce26136c8cc
    us-west-1:
      AMI: ami-0b606d7d59c68a5e0
    us-west-2:
      AMI: ami-0bf357e4bc8a8b9e3

Resources:

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
      GroupName: jenkins-sg
      GroupDescription: Security group for the jenkins server
      VpcId: !ImportValue CapstoneVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref JenkinsAllowedCIDR

  JenkinsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
      ImageId: !FindInMap [ AMIRegionMap, !Ref AWS::Region, AMI ]
      InstanceType: t3.nano
      SubnetId: !ImportValue CapstonePublicSubnet1ID
      UserData: !Base64 |
        #!/bin/sh
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get dist-upgrade -y
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
        echo 'deb https://pkg.jenkins.io/debian-stable binary/' > /etc/apt/sources.list.d/jenkins.list
        apt-get update -y
        apt-get install -y openjdk-8-jdk jenkins
        mkdir -p /etc/jenkins
        KEYSTORE_PASSWORD="`openssl rand -base64 32`"
        keytool -genkey -keyalg RSA -alias "jenkins" -keystore "/etc/jenkins/keystore.jks" -validity 365 -keysize 2048 -dname "CN=jenkins, OU=jenkins, O=jenkins, L=Munich, ST=Bavaria, C=DE" -ext SAN=dns:localhost -storepass "$KEYSTORE_PASSWORD"
        reboot
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup
      KeyName: !Ref JenkinsSSHKeyName
      SourceDestCheck: true
